[package]
name = "echo-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
structopt = { version = "0.3", default-features = false }
rand = "0.8"